variables:
  which_tests: 'all'

jobs:

- job: Linux
  strategy:
    matrix:
      py37:
        conda_env: py37
      py38:
        conda_env: py38
      py39:
        conda_env: py39
      py310:
        conda_env: py310
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: ci/azure/unit-tests.yml


- job: Windows
  strategy:
    matrix:
      py38:
        conda_env: py-win
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: ci/azure/unit-tests.yml


- job: MaxOSX
  strategy:
    matrix:
      py38:
        conda_env: py-mac
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: ci/azure/unit-tests.yml
