name: tests

on:
  workflow_dispatch:
  push:
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v3

    - name: Install micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: ci/requirements/py-base.yml
        environment-name: test-env
        extra-specs: python=${{ matrix.python-version }}
        cache-env: true

    - name: Test with pytest
      run: pytest --cov=autoray tests/ --cov-report=xml tests

    - name: Report to codecov
      uses: codecov/codecov-action@v3
